#include "scroll_system.hpp"
#include <algorithm>
#include "node_tree.hpp"
namespace ui
{
ScrollOffset ScrollState::maxOffset()const noexcept{return{std::max(0.0f,content.width-viewport.width),std::max(0.0f,content.height-viewport.height)};}
void ScrollState::clampOffset()noexcept{const auto max=maxOffset();offset.x=std::clamp(offset.x,0.0f,max.x);offset.y=std::clamp(offset.y,0.0f,max.y);}
bool ScrollSystem::registerScrollNode(Node&node){if(states_.contains(node.getId()))return false;states_.emplace(node.getId(),ScrollState{});return true;}bool ScrollSystem::unregisterScrollNode(NodeTree&,Node::Id nodeId){return states_.erase(nodeId)!=0;}bool ScrollSystem::isRegistered(Node::Id nodeId)const noexcept{return states_.contains(nodeId);}bool ScrollSystem::setOffset(Node::Id nodeId,const ScrollOffset&offset){auto it=states_.find(nodeId);if(it==states_.end())return false;it->second.offset=offset;it->second.clampOffset();return true;}bool ScrollSystem::scrollBy(Node::Id nodeId,const ScrollOffset&delta){auto it=states_.find(nodeId);if(it==states_.end())return false;it->second.offset=it->second.offset+delta;it->second.clampOffset();return true;}std::optional<ScrollState> ScrollSystem::getState(Node::Id nodeId)const{const auto it=states_.find(nodeId);if(it==states_.end())return std::nullopt;return it->second;}ScrollOffset ScrollSystem::getOffset(Node::Id nodeId)const noexcept{const auto it=states_.find(nodeId);return it==states_.end()?ScrollOffset{}:it->second.offset;}ScrollOffset ScrollSystem::getMaxOffset(Node::Id nodeId)const noexcept{const auto it=states_.find(nodeId);return it==states_.end()?ScrollOffset{}:it->second.maxOffset();}ScrollOffset ScrollSystem::getAccumulatedOffset(const Node&node)const noexcept{ScrollOffset result{};const Node*current=&node;while(current){if(const auto it=states_.find(current->getId());it!=states_.end())result=result+it->second.offset;current=current->getParent();}return result;}Node*ScrollSystem::findNearestScrollableAncestor(NodeTree&,Node*target)const noexcept{for(Node*current=target;current;current=current->getParent())if(isRegistered(current->getId()))return current;return nullptr;}bool ScrollSystem::handleWheel(NodeTree&nodeTree,float x,float y,float deltaX,float deltaY,const Node*modalRoot){Node*target=nodeTree.hitTest(x,y,modalRoot);Node*scrollNode=findNearestScrollableAncestor(nodeTree,target);if(!scrollNode)return false;return scrollBy(scrollNode->getId(),{deltaX,deltaY});}void ScrollSystem::sync(NodeTree&nodeTree){(void)nodeTree;for(auto&[id,state]:states_){(void)id;state.clampOffset();}}void ScrollSystem::clear(NodeTree&nodeTree)noexcept{(void)nodeTree;states_.clear();}
}
